[package]
name = "triplox-edn"
version = "0.1.0-alpha.1"
edition = "2021"
authors = ["Joe Walker <jwalker@mozilla.com>", "Finn Völkel <finn.volkel@gmail.com>"]

license = "Apache-2.0"
repository = "https://github.com/FiV0/triplox"
description = "EDN parser used by Triplox; a fork of the parser from Project Mentat."
readme = "./README.md"

[lib]
name = "edn"

[dependencies]
chrono = { workspace = true }
itertools = "0.14"
num = "0.4"
ordered-float = "4.0"
peg = "0.8"
pretty = "0.12"
uuid = { workspace = true, features = ["v4", "serde"] }
serde = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
serde_test = "1.0"
serde_json = "1.0"

[features]
serde_support = ["serde"]
