[storage]
type = "remote"
endpoint = "http://object-storage:9000"
bucket = "triplox"
access_key = "triplox"
secret_key = "triplox123"
cache_path = "/var/lib/triplox/disk"

[log]
type = "file"
path = "/var/lib/triplox/log/log"

[server]
host = "0.0.0.0"
port = 5490
