[storage]
type = "remote"
endpoint = "http://localhost:9000"
bucket = "triplox"
access_key = "triplox"
secret_key = "triplox123"
cache_path = "/tmp/triplox-disk"

[log]
type = "file"
path = "/tmp/triplox-log/log"

[server]
host = "127.0.0.1"
port = 5490
