[storage]
type = "remote"
endpoint = "http://localhost:9000"
bucket = "triplox"
access_key = "triplox"
secret_key = "triplox123"
file_log_path = "/tmp/triplox-log/log"

[local_disk_storage]
path = "/tmp/triplox-disk"

[server]
host = "127.0.0.1"
port = 5490
