[package]
name = "triplox-client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors = ["Finn Völkel <finn.volkel@gmail.com>"]
description = "HTTP/2 client for Triplox, a Datalog database."
readme = "README.md"
keywords = ["datalog", "database", "client"]
categories = ["database"]

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
edn = { workspace = true }
futures = "0.3"
reqwest = { workspace = true, features = ["stream"] }
rmp = { workspace = true }
rmpv = { workspace = true }
rkyv = { version = "0.7.45", features = ["std", "size_64", "validation"], default-features = false, optional = true }
serde = { workspace = true, features = ["derive"] }
size-of = { version = "0.1.7", package = "feldera-size-of", optional = true }
thiserror = { workspace = true }
tokio = { version = "1.40.0", features = ["rt", "sync"] }
tokio-util = { version = "0.7", features = ["io", "codec"] }
uuid = { workspace = true, features = ["serde"] }

[features]
dbsp = ["dep:rkyv", "dep:size-of"]

[dev-dependencies]
bincode = "1.3"
tokio = { version = "1.40.0", features = ["macros", "rt", "time"] }
