[package]
name = "examples"
version = "0.1.0"
edition = "2021"
publish = false
readme = "README.md"

[workspace]

[[bin]]
name = "simple-example"
path = "src/simple_example.rs"
test = false
bench = false

[[bin]]
name = "simple-example-edn"
path = "src/simple_example_edn.rs"
test = false
bench = false

[dependencies]
triplox = { path = "../.." }
edn = { package = "triplox-edn", path = "../../edn" }
anyhow = "1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
