name: Kafka Integration

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  kafka-integration-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@4be7066ada62dd38de10e7b70166bc74ed198c30 # stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - name: Run Kafka integration tests
        run: docker/scripts/run-kafka-integration-tests.sh
